# Generated by Django 4.2.28 on 2026-02-20 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('processing', 'Processing audio'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('uploader', models.CharField(blank=True, default='', max_length=200)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('error_message', models.TextField(blank=True, default='')),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
